test:
  url: "mongodb://localhost:27017/events_test"
  debug: true

development:
  url: "mongodb://localhost:27017/events_development"
  debug: true

production:
  url: "env:MONGODB_URL"
  debug: true

